services:
  app:
    build: ./app
    container_name: junto_app
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/status"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      redis-stack:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  redis-stack:
    image: redis/redis-stack:latest
    container_name: junto_redis
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASS}
    volumes: 
      - redis_data:/data/redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASS} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 3
  mongodb:
    image: mongo:8.0
    container_name: junto_mongo
    restart: unless-stopped
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u ${MONGO_USER} -p ${MONGO_PASS} --quiet
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  mongodb_data:
