sonar.projectKey=grauzonee_junto
sonar.organization=grauzonee

sonar.sources=app/src
sonar.tests=app/tests
sonar.test.inclusions=app/tests/**/*.test.ts

sonar.typescript.tsconfigPath=app/tsconfig.json
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info

sonar.exclusions=app/dist/**,app/coverage/**,app/node_modules/**,app/docs/**,app/src/seeders/**,app/src/scripts/**,app/src/openapi/**
sonar.coverage.exclusions=app/src/index.ts,app/src/scripts/**,app/src/seeders/**,app/src/openapi/**,app/src/types/**,app/src/**/*.d.ts
