name: Lint, test, compile

on:
  push:
    branches:
      - master    
  pull_request:
    branches:
      - master  

permissions:
  contents: read
  pull-requests: write

jobs:
  LintTestCompile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Docker
        uses: docker/setup-docker-action@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ./app

      - name: Run ESLint
        run: npm run lint
        working-directory: ./app
      
      - name: Run tests
        run: |
          npx jest --coverage | tee ./coverage.txt && exit ${PIPESTATUS[0]}
        working-directory: ./app

      - name: Jest Coverage Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./app/coverage/coverage-summary.json
          title: Junto Test Coverage
          summary-title: Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          coverage-title: Detailed Coverage
          coverage-path: ./app/coverage.txt

      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

      - name: Create the badge
        if: github.ref == 'refs/heads/master'
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
          gistID: 36cfc391c70f4ddf96bbd984c1276760
          filename: junto__master.json
          label: Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}%
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: javascript
          
