name: Lint, test, compile

on:
  push:
    branches:
      - master    
  pull_request:
    branches:
      - master  

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Docker
        uses: docker/setup-docker-action@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ./app

      - name: Run ESLint
        run: npm run lint
        working-directory: ./app
      
      - name: Run Tests
        run: npm run test
        working-directory: ./app

